services:

  # =========================
  # Backend API
  # =========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sso-backend
    ports:
      - "12080:12080"

    environment:
      HTTP_ADDR: "0.0.0.0:12080"
      FRONTEND_ORIGIN: "*"

      # PostgreSQL ที่มีอยู่แล้ว
      DATABASE_URL: "postgres://pguser:pgpass123@postgres_db:5432/postgres?sslmode=disable"

      DB_MAX_OPEN: "20"
      DB_MAX_LIFETIME_MIN: "30"

      JWT_SECRET: "dev-only-change-me-please-32-bytes-min!!"
      JWT_TTL_MINUTES: "480"

    networks:
      - sso-network

    restart: unless-stopped


  # =========================
  # API Gateway
  # =========================
  api_gateway:
    build:
      context: ./api_gatewayGo
      dockerfile: Dockerfile

    container_name: sso-gateway

    ports:
      - "18000:18000"

    environment:
      GATEWAY_ADDR: "0.0.0.0:18000"
      BACKEND_URL: "http://backend:12080"

    depends_on:
      - backend

    networks:
      - sso-network

    restart: unless-stopped


  # =========================
  # Frontend
  # =========================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: sso-frontend

    ports:
      - "3000:80"

    depends_on:
      - api_gateway

    networks:
      - sso-network

    restart: unless-stopped


# =========================
# Network
# =========================
networks:
  sso-network:
    driver: bridge